### ISSUE TITLE
Search bar for spawn menu

### ISSUE THREAD

**Issue by ATPGaming** [DeadJokerNotFunny/RHW-Bugs-And-Suggestions#39]
**What feature would you like to be added to the game**
Add a search bar to the spawn menu so we can find things easier

**How should it work**
It would be a search bar at the top of the spawn menu that you can type things in to find them

**Why should it be added**
So we can find things easier

**Comment by DeadJokerNotFunny18** [comment]
> **What feature would you like to be added to the game** Add a search bar to the spawn menu so we can find things easier
> 
> **How should it work** It would be a search bar at the top of the spawn menu that you can type things in to find them
> 
> **Why should it be added** So we can find things easier

Hey, ok, I will add search bar
