### ISSUE TITLE
BUG: When you copy/paste objects they paste inverted

### ISSUE THREAD

**Issue by TheIncubusS** [DeadJokerNotFunny/RHW-Bugs-And-Suggestions#42]
**Describe the bug**
When using the copy/paste feature the object that is pasted is facing the opposite direction it should be.

**To Reproduce**
Copy/paste an object with clear directional placement.

**Expected behavior**
For the object to paste exactly as it was copied.

**Comment by DeadJokerNotFunny18** [comment]
> **Describe the bug** When using the copy/paste feature the object that is pasted is facing the opposite direction it should be.
> 
> **To Reproduce** Copy/paste an object with clear directional placement.
> 
> **Expected behavior** For the object to paste exactly as it was copied.

Hello, to copy and paste, you don't need to hold Ctrl key. Just try to press C to copy and V to paste. If you press Ctrl + V to paste, it will flip the copied object.

**Comment by TheIncubusS** [comment]
AH! That makes sense. User error. Thanks for clarifying!
